//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX_TCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTrackingVT1
    {
        public System.Guid PK_Vehicle { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
        public double Altitude { get; set; }
        public string EngineStatus { get; set; }
        public double Course { get; set; }
        public double Temperature { get; set; }
        public double Fuel { get; set; }
        public string EventCode { get; set; }
        public Nullable<int> RemainingCash { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime ServerTime { get; set; }
        public Nullable<System.Guid> FK_Depo_In { get; set; }
        public Nullable<System.DateTime> DepoInDateTime { get; set; }
        public Nullable<System.Guid> FK_Depo_Out { get; set; }
        public Nullable<System.DateTime> DepoOutDateTime { get; set; }
        public string Status_PostionValidity { get; set; }
        public Nullable<int> Status_SateliteCount { get; set; }
        public Nullable<int> Status_GSMSignalStrength { get; set; }
        public string Event_BatteryLow { get; set; }
        public Nullable<System.DateTime> Event_BatteryLowAt { get; set; }
        public string Event_GSMSignalLost_Recovered { get; set; }
        public Nullable<System.DateTime> Event_GSMSignalLostRecoveredAt { get; set; }
        public Nullable<System.DateTime> EngineStatus_ChangedAt { get; set; }
        public Nullable<System.DateTime> Location_ChangedAt { get; set; }
        public Nullable<bool> Internal_ShowTemperature { get; set; }
        public string GpsIMEINumber { get; set; }
        public string GpsDeviceModel { get; set; }
        public Nullable<double> Speed { get; set; }
        public Nullable<decimal> Distance { get; set; }
    
        public virtual VehicleTrackingInformation VehicleTrackingInformation { get; set; }
    }
}
