//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX_TCP
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleTrackingInformation
    {
        public System.Guid PK_Vehicle { get; set; }
        public string GpsDeviceModel { get; set; }
        public string GpsIMEINumber { get; set; }
        public string GpsMobileNumber { get; set; }
        public Nullable<bool> Internal_ShowTemperature { get; set; }
        public Nullable<System.Guid> FK_AppUser_UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual VehicleTracking VehicleTracking { get; set; }
        public virtual VehicleTrackingVT1 VehicleTrackingVT1 { get; set; }
    }
}
