//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FX_TCP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class VTS_Entities : DbContext
    {
        public VTS_Entities()
            : base("name=VTS_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VehicleTracking> VehicleTrackings { get; set; }
        public virtual DbSet<VehicleTrackingInformation> VehicleTrackingInformations { get; set; }
        public virtual DbSet<VehicleTrackingVT1> VehicleTrackingVT1 { get; set; }
    
        public virtual ObjectResult<string> CleanDeviceData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("CleanDeviceData");
        }
    
        public virtual int DeleteCoreData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteCoreData");
        }
    
        public virtual int DeleteDbData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDbData");
        }
    
        public virtual int GenerateReport_GetVehicleHaltTime(string fK_Vehicle, Nullable<System.DateTime> startingDate, Nullable<System.DateTime> endingDate)
        {
            var fK_VehicleParameter = fK_Vehicle != null ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(string));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("startingDate", startingDate) :
                new ObjectParameter("startingDate", typeof(System.DateTime));
    
            var endingDateParameter = endingDate.HasValue ?
                new ObjectParameter("endingDate", endingDate) :
                new ObjectParameter("endingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateReport_GetVehicleHaltTime", fK_VehicleParameter, startingDateParameter, endingDateParameter);
        }
    
        public virtual int GenerateReport_GetVehicleHaltTime_Helper(string fK_Vehicle, Nullable<System.DateTime> startingDate, Nullable<System.DateTime> endingDate)
        {
            var fK_VehicleParameter = fK_Vehicle != null ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(string));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("startingDate", startingDate) :
                new ObjectParameter("startingDate", typeof(System.DateTime));
    
            var endingDateParameter = endingDate.HasValue ?
                new ObjectParameter("endingDate", endingDate) :
                new ObjectParameter("endingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateReport_GetVehicleHaltTime_Helper", fK_VehicleParameter, startingDateParameter, endingDateParameter);
        }
    
        public virtual int GenerateReport_GetVehicleHaltTime_Helper_Helper(string fK_Vehicle, Nullable<System.DateTime> startingDate)
        {
            var fK_VehicleParameter = fK_Vehicle != null ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(string));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("StartingDate", startingDate) :
                new ObjectParameter("StartingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GenerateReport_GetVehicleHaltTime_Helper_Helper", fK_VehicleParameter, startingDateParameter);
        }
    
        public virtual ObjectResult<string> MoveDeviceData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("MoveDeviceData");
        }
    
        public virtual ObjectResult<string> PushDeviceData__Insert(Nullable<System.Guid> pK_Vehicle, Nullable<System.DateTime> updateTime, string latitude, string longitude, string altitude, string engineStatus, string course, string temperature, string fuel, string speed, string distance)
        {
            var pK_VehicleParameter = pK_Vehicle.HasValue ?
                new ObjectParameter("PK_Vehicle", pK_Vehicle) :
                new ObjectParameter("PK_Vehicle", typeof(System.Guid));
    
            var updateTimeParameter = updateTime.HasValue ?
                new ObjectParameter("UpdateTime", updateTime) :
                new ObjectParameter("UpdateTime", typeof(System.DateTime));
    
            var latitudeParameter = latitude != null ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(string));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(string));
    
            var altitudeParameter = altitude != null ?
                new ObjectParameter("Altitude", altitude) :
                new ObjectParameter("Altitude", typeof(string));
    
            var engineStatusParameter = engineStatus != null ?
                new ObjectParameter("EngineStatus", engineStatus) :
                new ObjectParameter("EngineStatus", typeof(string));
    
            var courseParameter = course != null ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(string));
    
            var temperatureParameter = temperature != null ?
                new ObjectParameter("Temperature", temperature) :
                new ObjectParameter("Temperature", typeof(string));
    
            var fuelParameter = fuel != null ?
                new ObjectParameter("Fuel", fuel) :
                new ObjectParameter("Fuel", typeof(string));
    
            var speedParameter = speed != null ?
                new ObjectParameter("Speed", speed) :
                new ObjectParameter("Speed", typeof(string));
    
            var distanceParameter = distance != null ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PushDeviceData__Insert", pK_VehicleParameter, updateTimeParameter, latitudeParameter, longitudeParameter, altitudeParameter, engineStatusParameter, courseParameter, temperatureParameter, fuelParameter, speedParameter, distanceParameter);
        }
    
        public virtual ObjectResult<string> PushDeviceData_Insert_Insert(string gpsIMEINumber, Nullable<System.DateTime> updateTime, string latitude, string longitude, string altitude, string engineStatus, string course, string temperature, string fuel, string speed, string distance)
        {
            var gpsIMEINumberParameter = gpsIMEINumber != null ?
                new ObjectParameter("GpsIMEINumber", gpsIMEINumber) :
                new ObjectParameter("GpsIMEINumber", typeof(string));
    
            var updateTimeParameter = updateTime.HasValue ?
                new ObjectParameter("UpdateTime", updateTime) :
                new ObjectParameter("UpdateTime", typeof(System.DateTime));
    
            var latitudeParameter = latitude != null ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(string));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(string));
    
            var altitudeParameter = altitude != null ?
                new ObjectParameter("Altitude", altitude) :
                new ObjectParameter("Altitude", typeof(string));
    
            var engineStatusParameter = engineStatus != null ?
                new ObjectParameter("EngineStatus", engineStatus) :
                new ObjectParameter("EngineStatus", typeof(string));
    
            var courseParameter = course != null ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(string));
    
            var temperatureParameter = temperature != null ?
                new ObjectParameter("Temperature", temperature) :
                new ObjectParameter("Temperature", typeof(string));
    
            var fuelParameter = fuel != null ?
                new ObjectParameter("Fuel", fuel) :
                new ObjectParameter("Fuel", typeof(string));
    
            var speedParameter = speed != null ?
                new ObjectParameter("Speed", speed) :
                new ObjectParameter("Speed", typeof(string));
    
            var distanceParameter = distance != null ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PushDeviceData_Insert_Insert", gpsIMEINumberParameter, updateTimeParameter, latitudeParameter, longitudeParameter, altitudeParameter, engineStatusParameter, courseParameter, temperatureParameter, fuelParameter, speedParameter, distanceParameter);
        }
    
        public virtual ObjectResult<string> PushDeviceData_Update_Insert(Nullable<System.Guid> pK_Vehicle, Nullable<System.DateTime> updateTime, string latitude, string longitude, string altitude, string engineStatus, string course, string temperature, string fuel, string speed, string distance)
        {
            var pK_VehicleParameter = pK_Vehicle.HasValue ?
                new ObjectParameter("PK_Vehicle", pK_Vehicle) :
                new ObjectParameter("PK_Vehicle", typeof(System.Guid));
    
            var updateTimeParameter = updateTime.HasValue ?
                new ObjectParameter("UpdateTime", updateTime) :
                new ObjectParameter("UpdateTime", typeof(System.DateTime));
    
            var latitudeParameter = latitude != null ?
                new ObjectParameter("Latitude", latitude) :
                new ObjectParameter("Latitude", typeof(string));
    
            var longitudeParameter = longitude != null ?
                new ObjectParameter("Longitude", longitude) :
                new ObjectParameter("Longitude", typeof(string));
    
            var altitudeParameter = altitude != null ?
                new ObjectParameter("Altitude", altitude) :
                new ObjectParameter("Altitude", typeof(string));
    
            var engineStatusParameter = engineStatus != null ?
                new ObjectParameter("EngineStatus", engineStatus) :
                new ObjectParameter("EngineStatus", typeof(string));
    
            var courseParameter = course != null ?
                new ObjectParameter("Course", course) :
                new ObjectParameter("Course", typeof(string));
    
            var temperatureParameter = temperature != null ?
                new ObjectParameter("Temperature", temperature) :
                new ObjectParameter("Temperature", typeof(string));
    
            var fuelParameter = fuel != null ?
                new ObjectParameter("Fuel", fuel) :
                new ObjectParameter("Fuel", typeof(string));
    
            var speedParameter = speed != null ?
                new ObjectParameter("Speed", speed) :
                new ObjectParameter("Speed", typeof(string));
    
            var distanceParameter = distance != null ?
                new ObjectParameter("Distance", distance) :
                new ObjectParameter("Distance", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PushDeviceData_Update_Insert", pK_VehicleParameter, updateTimeParameter, latitudeParameter, longitudeParameter, altitudeParameter, engineStatusParameter, courseParameter, temperatureParameter, fuelParameter, speedParameter, distanceParameter);
        }
    
        public virtual ObjectResult<string> PushDeviceData_UpdateTime(Nullable<System.Guid> pK_Vehicle, Nullable<System.DateTime> updateTime)
        {
            var pK_VehicleParameter = pK_Vehicle.HasValue ?
                new ObjectParameter("PK_Vehicle", pK_Vehicle) :
                new ObjectParameter("PK_Vehicle", typeof(System.Guid));
    
            var updateTimeParameter = updateTime.HasValue ?
                new ObjectParameter("UpdateTime", updateTime) :
                new ObjectParameter("UpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("PushDeviceData_UpdateTime", pK_VehicleParameter, updateTimeParameter);
        }
    
        public virtual ObjectResult<Report_GetAccessibleEventList_InDateRange_Result> Report_GetAccessibleEventList_InDateRange(Nullable<System.Guid> fK_Vehicle)
        {
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetAccessibleEventList_InDateRange_Result>("Report_GetAccessibleEventList_InDateRange", fK_VehicleParameter);
        }
    
        public virtual ObjectResult<Report_GetTemperatureHistory_Result> Report_GetTemperatureHistory(string uSER_KEY, Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> startingDate, Nullable<System.DateTime> endingDate, Nullable<int> intervalMinute)
        {
            var uSER_KEYParameter = uSER_KEY != null ?
                new ObjectParameter("USER_KEY", uSER_KEY) :
                new ObjectParameter("USER_KEY", typeof(string));
    
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("StartingDate", startingDate) :
                new ObjectParameter("StartingDate", typeof(System.DateTime));
    
            var endingDateParameter = endingDate.HasValue ?
                new ObjectParameter("EndingDate", endingDate) :
                new ObjectParameter("EndingDate", typeof(System.DateTime));
    
            var intervalMinuteParameter = intervalMinute.HasValue ?
                new ObjectParameter("IntervalMinute", intervalMinute) :
                new ObjectParameter("IntervalMinute", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetTemperatureHistory_Result>("Report_GetTemperatureHistory", uSER_KEYParameter, fK_VehicleParameter, startingDateParameter, endingDateParameter, intervalMinuteParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleConsolidatedReport_Result> Report_GetVehicleConsolidatedReport(string uSER_KEY, Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> starTingDate)
        {
            var uSER_KEYParameter = uSER_KEY != null ?
                new ObjectParameter("USER_KEY", uSER_KEY) :
                new ObjectParameter("USER_KEY", typeof(string));
    
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var starTingDateParameter = starTingDate.HasValue ?
                new ObjectParameter("StarTingDate", starTingDate) :
                new ObjectParameter("StarTingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleConsolidatedReport_Result>("Report_GetVehicleConsolidatedReport", uSER_KEYParameter, fK_VehicleParameter, starTingDateParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleConsolidatedReport_ReadyReport_Result> Report_GetVehicleConsolidatedReport_ReadyReport(Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> startingDate)
        {
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("StartingDate", startingDate) :
                new ObjectParameter("StartingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleConsolidatedReport_ReadyReport_Result>("Report_GetVehicleConsolidatedReport_ReadyReport", fK_VehicleParameter, startingDateParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleHaltTime_Result> Report_GetVehicleHaltTime(string uSER_KEY, Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> startingDate, Nullable<System.DateTime> endingDate, Nullable<int> mininumMinuteDealy)
        {
            var uSER_KEYParameter = uSER_KEY != null ?
                new ObjectParameter("USER_KEY", uSER_KEY) :
                new ObjectParameter("USER_KEY", typeof(string));
    
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("StartingDate", startingDate) :
                new ObjectParameter("StartingDate", typeof(System.DateTime));
    
            var endingDateParameter = endingDate.HasValue ?
                new ObjectParameter("EndingDate", endingDate) :
                new ObjectParameter("EndingDate", typeof(System.DateTime));
    
            var mininumMinuteDealyParameter = mininumMinuteDealy.HasValue ?
                new ObjectParameter("MininumMinuteDealy", mininumMinuteDealy) :
                new ObjectParameter("MininumMinuteDealy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleHaltTime_Result>("Report_GetVehicleHaltTime", uSER_KEYParameter, fK_VehicleParameter, startingDateParameter, endingDateParameter, mininumMinuteDealyParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleHaltTime_ReadyReport_Result> Report_GetVehicleHaltTime_ReadyReport(Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> startingDate, Nullable<System.DateTime> endingDate, Nullable<int> mininumMinuteDealy)
        {
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("StartingDate", startingDate) :
                new ObjectParameter("StartingDate", typeof(System.DateTime));
    
            var endingDateParameter = endingDate.HasValue ?
                new ObjectParameter("EndingDate", endingDate) :
                new ObjectParameter("EndingDate", typeof(System.DateTime));
    
            var mininumMinuteDealyParameter = mininumMinuteDealy.HasValue ?
                new ObjectParameter("MininumMinuteDealy", mininumMinuteDealy) :
                new ObjectParameter("MininumMinuteDealy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleHaltTime_ReadyReport_Result>("Report_GetVehicleHaltTime_ReadyReport", fK_VehicleParameter, startingDateParameter, endingDateParameter, mininumMinuteDealyParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleHistory_Result> Report_GetVehicleHistory(string uSER_KEY, Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> startingDate, Nullable<System.DateTime> endingDate, Nullable<int> timeLapMinute)
        {
            var uSER_KEYParameter = uSER_KEY != null ?
                new ObjectParameter("USER_KEY", uSER_KEY) :
                new ObjectParameter("USER_KEY", typeof(string));
    
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("StartingDate", startingDate) :
                new ObjectParameter("StartingDate", typeof(System.DateTime));
    
            var endingDateParameter = endingDate.HasValue ?
                new ObjectParameter("EndingDate", endingDate) :
                new ObjectParameter("EndingDate", typeof(System.DateTime));
    
            var timeLapMinuteParameter = timeLapMinute.HasValue ?
                new ObjectParameter("TimeLapMinute", timeLapMinute) :
                new ObjectParameter("TimeLapMinute", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleHistory_Result>("Report_GetVehicleHistory", uSER_KEYParameter, fK_VehicleParameter, startingDateParameter, endingDateParameter, timeLapMinuteParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleHistoryDetail_Result> Report_GetVehicleHistoryDetail(Nullable<System.Guid> uSER_KEY, Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> startingDate, Nullable<System.DateTime> endingDate)
        {
            var uSER_KEYParameter = uSER_KEY.HasValue ?
                new ObjectParameter("USER_KEY", uSER_KEY) :
                new ObjectParameter("USER_KEY", typeof(System.Guid));
    
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var startingDateParameter = startingDate.HasValue ?
                new ObjectParameter("StartingDate", startingDate) :
                new ObjectParameter("StartingDate", typeof(System.DateTime));
    
            var endingDateParameter = endingDate.HasValue ?
                new ObjectParameter("EndingDate", endingDate) :
                new ObjectParameter("EndingDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleHistoryDetail_Result>("Report_GetVehicleHistoryDetail", uSER_KEYParameter, fK_VehicleParameter, startingDateParameter, endingDateParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleLastUpdate_withNearMapLocation_Result> Report_GetVehicleLastUpdate_withNearMapLocation(Nullable<System.Guid> pK_User)
        {
            var pK_UserParameter = pK_User.HasValue ?
                new ObjectParameter("PK_User", pK_User) :
                new ObjectParameter("PK_User", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleLastUpdate_withNearMapLocation_Result>("Report_GetVehicleLastUpdate_withNearMapLocation", pK_UserParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleTracking_Result> Report_GetVehicleTracking(Nullable<System.Guid> pK_User)
        {
            var pK_UserParameter = pK_User.HasValue ?
                new ObjectParameter("PK_User", pK_User) :
                new ObjectParameter("PK_User", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleTracking_Result>("Report_GetVehicleTracking", pK_UserParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleTracking_Single_Result> Report_GetVehicleTracking_Single(Nullable<System.Guid> pK_Vehicle)
        {
            var pK_VehicleParameter = pK_Vehicle.HasValue ?
                new ObjectParameter("PK_Vehicle", pK_Vehicle) :
                new ObjectParameter("PK_Vehicle", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleTracking_Single_Result>("Report_GetVehicleTracking_Single", pK_VehicleParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleTrackingByDepoGroup_Result> Report_GetVehicleTrackingByDepoGroup(Nullable<System.Guid> pK_DepoGroup)
        {
            var pK_DepoGroupParameter = pK_DepoGroup.HasValue ?
                new ObjectParameter("PK_DepoGroup", pK_DepoGroup) :
                new ObjectParameter("PK_DepoGroup", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleTrackingByDepoGroup_Result>("Report_GetVehicleTrackingByDepoGroup", pK_DepoGroupParameter);
        }
    
        public virtual ObjectResult<Report_GetVehicleTrackingForIndividualRequisition_Result> Report_GetVehicleTrackingForIndividualRequisition(Nullable<System.Guid> pK_IndividualRequisition)
        {
            var pK_IndividualRequisitionParameter = pK_IndividualRequisition.HasValue ?
                new ObjectParameter("PK_IndividualRequisition", pK_IndividualRequisition) :
                new ObjectParameter("PK_IndividualRequisition", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Report_GetVehicleTrackingForIndividualRequisition_Result>("Report_GetVehicleTrackingForIndividualRequisition", pK_IndividualRequisitionParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<Tracking_GetLastDeviceData_Result> Tracking_GetLastDeviceData(Nullable<System.Guid> fK_Vehicle)
        {
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tracking_GetLastDeviceData_Result>("Tracking_GetLastDeviceData", fK_VehicleParameter);
        }
    
        public virtual ObjectResult<Tracking_GetNextDeviceData_Result> Tracking_GetNextDeviceData(Nullable<System.Guid> fK_Vehicle, Nullable<System.DateTime> previousUpdateTime)
        {
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var previousUpdateTimeParameter = previousUpdateTime.HasValue ?
                new ObjectParameter("PreviousUpdateTime", previousUpdateTime) :
                new ObjectParameter("PreviousUpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Tracking_GetNextDeviceData_Result>("Tracking_GetNextDeviceData", fK_VehicleParameter, previousUpdateTimeParameter);
        }
    
        public virtual int VehicleInDepo_Insert(Nullable<System.Guid> fK_Vehicle, Nullable<System.Guid> fK_Depo, Nullable<System.DateTime> updateTime)
        {
            var fK_VehicleParameter = fK_Vehicle.HasValue ?
                new ObjectParameter("FK_Vehicle", fK_Vehicle) :
                new ObjectParameter("FK_Vehicle", typeof(System.Guid));
    
            var fK_DepoParameter = fK_Depo.HasValue ?
                new ObjectParameter("FK_Depo", fK_Depo) :
                new ObjectParameter("FK_Depo", typeof(System.Guid));
    
            var updateTimeParameter = updateTime.HasValue ?
                new ObjectParameter("UpdateTime", updateTime) :
                new ObjectParameter("UpdateTime", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("VehicleInDepo_Insert", fK_VehicleParameter, fK_DepoParameter, updateTimeParameter);
        }
    }
}
